import type { Metadata } from "next";
import { Onest, Cutive_Mono } from "next/font/google";
import "./ui/globals.css";
import Background from "./ui/background";

const onest = Onest({
  variable: "--font-onest",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const cutiveMono = Cutive_Mono({
  variable: "--font-cutive-mono",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${onest.variable} ${cutiveMono.variable} antialiased`}
      >
      <Background />
        {children}
      </body>
    </html>
  );
}
