import type { Metadata } from "next";
import { Onest, Ubuntu_Mono } from "next/font/google";
import "./ui/globals.css";
import Background from "./ui/background";

const onest = Onest({
  variable: "--font-onest",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const ubuntuMono = Ubuntu_Mono({
  variable: "--font-ubuntu-mono",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${onest.variable} ${ubuntuMono.variable} antialiased`}
      >
      <Background />
        {children}
      </body>
    </html>
  );
}
